/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2018-12-05 16:10:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mybean.data.DataByPage;
import com.sun.rowset.*;

public final class byPageShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/head.txt", Long.valueOf(1544023860541L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.sun.rowset");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mybean.data.DataByPage");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GB2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      mybean.data.DataByPage dataBean = null;
      synchronized (session) {
        dataBean = (mybean.data.DataByPage) _jspx_page_context.getAttribute("dataBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (dataBean == null){
          dataBean = new mybean.data.DataByPage();
          _jspx_page_context.setAttribute("dataBean", dataBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div align=\"center\"> \r\n");
      out.write("  <Font color=red><H3>“青山不老绿水无忧”化妆品销售网</H3></Font>\r\n");
      out.write("  <table  cellSpacing=\"1\" cellPadding=\"1\" width=\"660\" align=\"center\" border=\"0\">\r\n");
      out.write("   <tr valign=\"bottom\">\r\n");
      out.write("   <td><A href=\"inputRegisterMess.jsp\">注册</font></A></td>\r\n");
      out.write("   <td><A href=\"login.jsp\">登录</A></td>\r\n");
      out.write("   <td><A href=\"lookCosmetic.jsp\">浏览化妆品</A></td>\r\n");
      out.write("   <td><A href=\"searchCosmetic.jsp\">查询化妆品</A></td>\r\n");
      out.write("   <td><A href=\"lookShoppingCar.jsp\">查看购物车</A></td>\r\n");
      out.write("   <td><A href=\"lookOrderForm.jsp\">查看订单</A></td>\r\n");
      out.write("   <td><A href=\"exitServlet\">退出</A></td>\r\n");
      out.write("   <td><A href=\"index.jsp\">主页</A></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<HTML><Body background=image/back.jpg><center>\r\n");
      out.write("<BR>当前显示的内容是：\r\n");
      out.write("  <table border=2>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>化妆品标识号</th>\r\n");
      out.write("    <th>化妆品名称</th>\r\n");
      out.write("    <th>化妆品制造商</th>\r\n");
      out.write("    <th>化妆品价格</th>\r\n");
      out.write("    <th>查看详情</th>\r\n");
      out.write("    <td><font color=blue>添加到购物车</font></td>\r\n");
      out.write("  </tr>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("dataBean"), "pageSize", request.getParameter("pageSize"), request, "pageSize", false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("dataBean"), "currentPage", request.getParameter("currentPage"), request, "currentPage", false);
      out.write('\r');
      out.write('\n');
    
      CachedRowSetImpl rowSet=dataBean.getRowSet();
      if(rowSet==null) {
         out.print("没有任何查询信息，无法浏览");
         return;  
      }
      rowSet.last(); 
      int totalRecord=rowSet.getRow();
      out.println("全部记录数"+totalRecord); //全部记录数
      int pageSize=dataBean.getPageSize();  //每页显示的记录数
      int totalPages = dataBean.getTotalPages();
      if(totalRecord%pageSize==0)
           totalPages = totalRecord/pageSize;//总页数
      else
           totalPages = totalRecord/pageSize+1;
      dataBean.setPageSize(pageSize);
      dataBean.setTotalPages(totalPages);
      if(totalPages>=1) {
         if(dataBean.getCurrentPage()<1)
              dataBean.setCurrentPage(dataBean.getTotalPages());
         if(dataBean.getCurrentPage()>dataBean.getTotalPages())
              dataBean.setCurrentPage(1);
         int index=(dataBean.getCurrentPage()-1)*pageSize+1;
         rowSet.absolute(index);  //查询位置移动到currentPage页起始位置
         boolean boo=true;
         for(int i=1;i<=pageSize&&boo;i++) { 
            String number=rowSet.getString(1);
            String name=rowSet.getString(2);
            String maker=rowSet.getString(3);
            String price=rowSet.getString(4);
            String goods =
            "("+number+","+name+","+maker+
             ","+price+")#"+price;//便于购物车计算价格,尾缀上"#价格值"
            goods = goods.replaceAll("\\p{Blank}","");
            String button="<form  action='putGoodsServlet' method = 'post'>"+
                     "<input type ='hidden' name='java' value= "+goods+">"+
                     "<input type ='submit'  value='放入购物车' ></form>";
            String detail="<form  action='showDetail.jsp' method = 'post'>"+
                     "<input type ='hidden' name='xijie' value= "+number+">"+
                     "<input type ='submit'  value='查看细节' ></form>";
            out.print("<tr>");
            out.print("<td>"+number+"</td>");
            out.print("<td>"+name+"</td>");
            out.print("<td>"+maker+"</td>");
            out.print("<td>"+price+"</td>");
            out.print("<td>"+detail+"</td>");
            out.print("<td>"+button+"</td>");
            out.print("</tr>");
            boo=rowSet.next();
         }
     }

      out.write("\r\n");
      out.write(" </table>\r\n");
      out.write(" <BR>每页最多显示");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.DataByPage)_jspx_page_context.findAttribute("dataBean")).getPageSize())));
      out.write("条信息\r\n");
      out.write(" <BR>当前显示第<Font color=blue>\r\n");
      out.write("     ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.DataByPage)_jspx_page_context.findAttribute("dataBean")).getCurrentPage())));
      out.write("\r\n");
      out.write("   </Font>页,共有\r\n");
      out.write("   <Font color=blue>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.DataByPage)_jspx_page_context.findAttribute("dataBean")).getTotalPages())));
      out.write("\r\n");
      out.write("   </Font>页。\r\n");
      out.write("<Table>\r\n");
      out.write("  <tr><td><FORM action=\"\" method=post>\r\n");
      out.write("          <Input type=hidden name=\"currentPage\" value=\r\n");
      out.write("         \"");
      out.print(dataBean.getCurrentPage()-1 );
      out.write("\">\r\n");
      out.write("           <Input type=submit name=\"g\" value=\"上一页\"></FORM></td>\r\n");
      out.write("      <td><FORM action=\"\" method=post>\r\n");
      out.write("          <Input type=hidden name=\"currentPage\"\r\n");
      out.write("           value=\"");
      out.print(dataBean.getCurrentPage()+1 );
      out.write("\">\r\n");
      out.write("          <Input type=submit name=\"g\" value=\"下一页\"></FORM></td></tr>\r\n");
      out.write(" <tr><td> <FORM action=\"\" method=post>\r\n");
      out.write("          每页显示<Input type=text name=\"pageSize\" value =1 size=3>\r\n");
      out.write("          条记录<Input type=submit name=\"g\" value=\"确定\"></FORM></td>\r\n");
      out.write("      <td> <FORM action=\"\" method=post>\r\n");
      out.write("           输入页码：<Input type=text name=\"currentPage\" size=2 >\r\n");
      out.write("           <Input type=submit name=\"g\" value=\"提交\"></FORM></td></tr>\r\n");
      out.write("</Table>\r\n");
      out.write("</Center>\r\n");
      out.write("</BODY></HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
