/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2018-12-05 16:10:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inputRegisterMess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/head.txt", Long.valueOf(1544023860541L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GB2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      mybean.data.Register userBean = null;
      userBean = (mybean.data.Register) _jspx_page_context.getAttribute("userBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (userBean == null){
        userBean = new mybean.data.Register();
        _jspx_page_context.setAttribute("userBean", userBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("<HEAD>");
      out.write("\r\n");
      out.write("<div align=\"center\"> \r\n");
      out.write("  <Font color=red><H3>“青山不老绿水无忧”化妆品销售网</H3></Font>\r\n");
      out.write("  <table  cellSpacing=\"1\" cellPadding=\"1\" width=\"660\" align=\"center\" border=\"0\">\r\n");
      out.write("   <tr valign=\"bottom\">\r\n");
      out.write("   <td><A href=\"inputRegisterMess.jsp\">注册</font></A></td>\r\n");
      out.write("   <td><A href=\"login.jsp\">登录</A></td>\r\n");
      out.write("   <td><A href=\"lookCosmetic.jsp\">浏览化妆品</A></td>\r\n");
      out.write("   <td><A href=\"searchCosmetic.jsp\">查询化妆品</A></td>\r\n");
      out.write("   <td><A href=\"lookShoppingCar.jsp\">查看购物车</A></td>\r\n");
      out.write("   <td><A href=\"lookOrderForm.jsp\">查看订单</A></td>\r\n");
      out.write("   <td><A href=\"exitServlet\">退出</A></td>\r\n");
      out.write("   <td><A href=\"index.jsp\">主页</A></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<title>注册页面</title>\r\n");
      out.write("<HTML><BODY background=image/back.jpg><Font size=2>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<FORM action=\"registerServlet\" method=\"post\" name=form>\r\n");
      out.write("<table>\r\n");
      out.write("    用户名由字母、数字、下划线构成，*注释的项必须填写。\r\n");
      out.write("   <tr><td>*用户名称:</td><td><Input type=text name=\"logname\" ></td>\r\n");
      out.write("       <td>*用户密码:</td><td><Input type=password name=\"password\">\r\n");
      out.write("       </td></tr>\r\n");
      out.write("   <tr><td>*重复密码:</td><td>\r\n");
      out.write("       <Input type=password name=\"again_password\"></td>\r\n");
      out.write("       <td>联系电话:</td><td><Input type=text name=\"phone\"></td></tr>\r\n");
      out.write("   <tr><td>邮寄地址:</td><td><Input type=text name=\"address\"></td>\r\n");
      out.write("       <td>真实姓名:</td><td><Input type=text name=\"realname\"></td>\r\n");
      out.write("       <td><Input type=submit name=\"g\" value=\"提交\"></td> </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</Form>\r\n");
      out.write("</div >\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<p> 注册反馈：\r\n");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Register)_jspx_page_context.findAttribute("userBean")).getBackNews())));
      out.write(" \r\n");
      out.write("<table border=3>\r\n");
      out.write("     <tr><td>会员名称:</td>\r\n");
      out.write("     <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Register)_jspx_page_context.findAttribute("userBean")).getLogname())));
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr><td>姓名:</td>\r\n");
      out.write("     <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Register)_jspx_page_context.findAttribute("userBean")).getRealname())));
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr><td>地址:</td>\r\n");
      out.write("     <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Register)_jspx_page_context.findAttribute("userBean")).getAddress())));
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr><td>电话:</td>\r\n");
      out.write("     <td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Register)_jspx_page_context.findAttribute("userBean")).getPhone())));
      out.write("</td>\r\n");
      out.write("     </tr>\r\n");
      out.write("</table></div >\r\n");
      out.write("</Body></HTML>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
