/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2021-10-26 02:32:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mybean.data.Login;

public final class showLoginMess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/head.txt", Long.valueOf(1397800415759L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mybean.data.Login");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=GB2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      mybean.data.Login login = null;
      synchronized (session) {
        login = (mybean.data.Login) _jspx_page_context.getAttribute("login", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (login == null){
          throw new java.lang.InstantiationException("bean login not found within scope");
        }
      }
      out.write("\r\n");
      out.write("<HEAD>");
      out.write("\r\n");
      out.write("<CENTER><Font size=5><P>交友信息发布网</Font></CENTER>\r\n");
      out.write("<table  cellSpacing=\"1\" cellPadding=\"1\" width=\"560\" align=\"center\" border=\"0\" >\r\n");
      out.write("   <tr valign=\"bottom\">\r\n");
      out.write("   <td><A href=\"register.jsp\"><font size=2>会员注册</font></A></td>\r\n");
      out.write("   <td><A href=\"login.jsp\"><font size=2>会员登录</font></A></td>\r\n");
      out.write("   <td><A href=\"upload.jsp\"><font size=2>上传照片</font></A></td>\r\n");
      out.write("   <td><A href=\"choiceLookType.jsp\"><font size=2>浏览会员</font></A></td>\r\n");
      out.write("   <td><A href=\"inputModifyMess.jsp\"><font size=2>修改注册信息</font></A></td>\r\n");
      out.write("   <td><A href=\"modifyPassword.jsp\"><font size=2>修改密码</font></A></td>\r\n");
      out.write("   <td><A href=\"helpExitLogin\"><font size=2>退出登录</font></A></td>\r\n");
      out.write("   <td><A href=\"index.jsp\"><font size=2>返回主页</font></A></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </Font>\r\n");
      out.write("</table>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<HTML>\r\n");
      out.write("<BODY bgcolor=pink>\r\n");
      out.write("  <CENTER>\r\n");
      out.write("  <Font size=4 color=blue >\r\n");
      out.write("  <BR>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getBackNews())));
      out.write("\r\n");
      out.write("  </Font> \r\n");
      out.write(" <Font size=2 color=cyan>\r\n");
      out.write(" ");
 if(login.getSuccess()==true)
     {
 
      out.write("    <BR>登录会员名称:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getLogname())));
      out.write('\r');
      out.write('\n');
      out.write(' ');
  }
   else
    { 
 
      out.write("  <BR>登录会员名称:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getLogname())));
      out.write("\r\n");
      out.write("     <BR>登录会员密码:");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((mybean.data.Login)_jspx_page_context.findAttribute("login")).getPassword())));
      out.write('\r');
      out.write('\n');
      out.write(' ');
 }
 
      out.write("\r\n");
      out.write(" </FONT>\r\n");
      out.write(" </CENTER>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
